rrr

diff --git a/basics_1/1-show_attached_IPs b/basics_1/1-show_attached_IPs
--- a/basics_1/1-show_attached_IPs
+++ b/basics_1/1-show_attached_IPs
@@ -1,4 +1,17 @@
 #!/usr/bin/env bash
-# Script tp display all IPV4 IPS on a machine
+# Script that displays all active IPv4 IPs on the machine
 
-ifconfig -a | grep inet | cut -d: -f2 | cut -d" "  -f1
+# Using 'ip' command (modern approach)
+if command -v ip >/dev/null 2>&1; then
+    ip -4 addr show | grep -o 'inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' | cut -d' ' -f2 | sort
+# Using 'ifconfig' as fallback (older systems)
+elif command -v ifconfig >/dev/null 2>&1; then
+    ifconfig | grep -o 'inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' | cut -d' ' -f2 | sort
+# Using hostname as a last resort
+elif command -v hostname >/dev/null 2>&1; then
+    hostname -I | tr ' ' '\n' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+
+ | sort
+else
+    echo "Error: No suitable tools found to retrieve IP addresses." >&2
+    exit 1
+fi
